version: "3.9"

services:
  app:
    container_name: gosvc_container
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_DB=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    build:
      context: ./project-my-dockerfile/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - 4331:77
    networks:
      - net_mycompose_yusicantik

  postgresdb:
    image: postgres:latest
    container_name: dbsvc_container
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_NAME=${DB_NAME}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - vol_mycompose_yusicantik:/var/lib/postgresql/data
    networks:
      - net_mycompose_yusicantik

volumes:
  vol_mycompose_yusicantik:

networks:
  net_mycompose_yusicantik:
    driver: bridge
